### ISSUE TITLE
Make Leaderboard Page

### ISSUE THREAD

**Issue by batflarrow** [iiitv/CTF-frontend#6]

**Comment by Safwan310** [comment]
Hey can I be assigned with this issue @batflarrow

**Comment by raghusodani** [comment]
@iiitv/project-maintainers Can I work on this?

**Comment by Shreyansh-Mishra** [comment]
GFI @raghusodani 👍🏽

**Comment by batflarrow** [comment]
Any updates @raghusodani

**Comment by raghusodani** [comment]
working on it....will commit today.

**Comment by batflarrow** [comment]
> working on it....will commit today.

Ohk great!
